export const MISSING_BUCKET_OR_TABLE_NAME = 'Missing BUCKET_NAME or TABLE_NAME environment variables';
export const MISSING_SUB = 'Missing users sub in post-signup event!';
export const MISSING_NAME = 'Missing users name in post-signup event!';
export const MISSING_EMAIL = 'Missing users email in post-signup event!';
export const MISSING_EMAIL_VERIFIED = 'Missing email verified indicator in post-signup event!';
export const MISSING_GIVEN_NAME = 'Missing users given name in post-signup event!';
export const MISSING_FAMILY_NAME = 'Missing users family name in post-signup event!';
export const S3_FAILED = 'Error: User Directory Creation Failed!';
export const DYNAMO_FAILED = 'Error: User Table Entry Failed!';